# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-27 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_auto_20160727_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
